version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: delivery-db
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./mysql:/var/lib/mysql
